// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECR--I_R5cKLMd3qX6zHEETqPHKux3yk',
    appId: '1:106978689703:web:22120bedb80391e3a85182',
    messagingSenderId: '106978689703',
    projectId: 'fir-expense-notes',
    authDomain: 'fir-expense-notes.firebaseapp.com',
    databaseURL: 'https://fir-expense-notes-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-expense-notes.appspot.com',
    measurementId: 'G-YL8G8X36MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqoo_07zeJpdGVXT8wz_Du_-6MZS1--ns',
    appId: '1:106978689703:android:a3b159bb2a0a4f3aa85182',
    messagingSenderId: '106978689703',
    projectId: 'fir-expense-notes',
    databaseURL: 'https://fir-expense-notes-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-expense-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB8LIEvUzTJSyYx1mebZdGu_o0SXwenE8',
    appId: '1:106978689703:ios:17adb58a64c0d190a85182',
    messagingSenderId: '106978689703',
    projectId: 'fir-expense-notes',
    databaseURL: 'https://fir-expense-notes-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-expense-notes.appspot.com',
    iosClientId: '106978689703-ildm0uns90j96cvd0sauv2ib3s640no9.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseNotes',
  );
}
